<?php

/**
 * @file
 * The main module file for the islandora_solr_metadata module.
 */

/**
 * Implements hook_theme().
 */
function islandora_solr_metadata_theme() {
  return [
    'islandora_solr_metadata_display' => [
      'template' => 'theme/islandora-solr-metadata-display',
      // We can add PIDs to the end of this pattern in our preprocess function
      // and templates will be able to have have a pid appended to the
      // template name to overide a template on a per object basis.
      // An example template might be named:
      // "islandora-solr-metadata-display--islandora-27.tpl.php".
      'pattern' => 'islandora_solr_metadata_display__',
      'variables' => [
        'islandora_object' => NULL,
        'print' => FALSE,
        'solr_fields' => [],
        'found' => FALSE,
        'associations' => [],
      ],
      'file' => 'theme/theme.inc',
    ],
    'islandora_solr_metadata_description' => [
      'template' => 'theme/islandora-solr-metadata-description',
      // We can add PIDs to the end of this pattern in our preprocess function
      // and templates will be able to have have a pid appended to the
      // template name to overide a template on a per object basis.
      // An example template might be named:
      // "islandora-solr-metadata-description--islandora-27.tpl.php".
      'pattern' => 'islandora_solr_metadata_description__',
      'variables' => [
        'islandora_object' => NULL,
        'solr_fields' => [],
        'combine' => TRUE,
        'found' => FALSE,
        'associations' => [],
      ],
      'file' => 'theme/theme.inc',
    ],
  ];
}

/**
 * Access callback for accessing a configuration based upon ID.
 *
 * @param int $configuration_id
 *   The configuration ID of the list we are accessing.
 *
 * @return bool
 *   TRUE if the user has permission and the list exists, FALSE otherwise.
 */
function islandora_solr_metadata_access($configuration_id) {
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  return islandora_solr_metadata_configuration_exists($configuration_id) && \Drupal::currentUser()->hasPermission('administer islandora_solr_metadata');
}

/**
 * Access callback for accessing field configuration.
 *
 * @param int $configuration_id
 *   The configuration ID of the list we are accessing.
 * @param string $escaped_field
 *   The name of the Solr field with slashes escaped, as per
 *   islandora_solr_replace_slashes().
 *
 * @return bool
 *   TRUE if the user has access to the configuration and the field exists in
 *   the configuration, FALSE otherwise.
 */
function islandora_solr_metadata_field_configuration_access($configuration_id, $escaped_field) {
  module_load_include('inc', 'islandora_solr', 'includes/utilities');
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  return islandora_solr_metadata_access($configuration_id) && array_key_exists(islandora_solr_restore_slashes($escaped_field), islandora_solr_metadata_get_fields($configuration_id, FALSE));
}

/**
 * Implements hook_features_api().
 */
function islandora_solr_metadata_features_api() {
  $mod_path = drupal_get_path('module', 'islandora_solr_metadata');
  return [
    'islandora_solr_metadata_configurations' => [
      'name' => t('Islandora Solr Metadata Configurations'),
      'file' => "$mod_path/includes/configurations.features.inc",
      'default_hook' => 'islandora_solr_metadata_configurations_default_fields',
      'feature_source' => TRUE,
    ],
  ];
}

/**
 * Title callback for the configuration display.
 *
 * @param int $configuration_id
 *   The ID of the configuration we are retrieving the name of.
 *
 * @return string
 *   The name of the configuration that is to be edited.
 */
function islandora_solr_metadata_display_configuration_name($configuration_id) {
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  $configuration_name = islandora_solr_metadata_retrieve_configuration_name($configuration_id);
  return t('@configuration_name display configuration', [
    '@configuration_name' => $configuration_name,
  ]);
}

/**
 * Title callback for the field configuration display.
 *
 * @param int $configuration_id
 *   The ID of the configuration we are retrieving the name of.
 *
 * @return string
 *   The name of the configuration that is to be edited.
 */
function islandora_solr_metadata_display_field_configuration_name($configuration_id, $escaped_field_name) {
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  module_load_include('inc', 'islandora_solr', 'includes/utilities');

  return $this->t('@field configuration', array(
    '@field' => islandora_solr_restore_slashes($escaped_field_name),
  ));
}

/**
 * Implements hook_i18n_string_info().
 */
function islandora_solr_metadata_i18n_string_info() {
  return [
    'islandora_solr_metadata' => [
      'title' => t('Islandora Solr Metadata'),
      'description' => t('Translatable configuration names and display labels.'),
      'format' => FALSE,
      'list' => TRUE,
    ],
  ];
}

/**
 * Implements hook_islandora_metadata_display_info().
 */
function islandora_solr_metadata_islandora_metadata_display_info() {
  return [
    'islandora_solr_metadata' => [
      'label' => t('Islandora Solr Metadata'),
      'description' => t('Metadata display driven by the Islandora Solr Search module'),
      'metadata callback' => 'islandora_solr_metadata_display_callback',
      'description callback' => 'islandora_solr_metadata_description_callback',
      'configuration' => 'admin/islandora/search/islandora_solr/metadata',
    ],
  ];
}

/**
 * Metadata display callback for rendering metadata from Solr.
 *
 * @param AbstractObject $object
 *   An AbstractObject representing an object within Fedora.
 * @param bool $print
 *   Whether this is for printing purposes.
 *
 * @return string
 *   Markup representing the metadata display pulled from Solr.
 */
function islandora_solr_metadata_display_callback(AbstractObject $object, $print = FALSE) {
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  $elements = [
    '#islandora_object' => $object,
    '#print' => $print,
    '#associations' => islandora_solr_metadata_get_associations_by_cmodels($object->models),
  ];
  \Drupal::moduleHandler()->alter('islandora_solr_metadata_display_elements', $elements);
  if (count($elements['#associations']) > 0) {
    $markup = [
      '#theme' => 'islandora_solr_metadata_display',
    ] + $elements;
    return $markup;
  }
  else {
    return FALSE;
  }
}

/**
 * Metadata display callback for rendering metadata from Solr.
 *
 * @param AbstractObject $object
 *   An AbstractObject representing an object within Fedora.
 *
 * @return string
 *   Markup representing the metadata display pulled from Solr.
 */
function islandora_solr_metadata_description_callback(AbstractObject $object) {
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  module_load_include('module', 'islandora');
  $object = islandora_object_load($object->id);
  $elements = [
    '#islandora_object' => $object,
    '#associations' => islandora_solr_metadata_get_associations_by_cmodels($object->models),
  ];
  \Drupal::moduleHandler()->alter('islandora_solr_metadata_description_elements', $elements);
  if (count($elements['#associations']) > 0) {
    $markup = [
      '#theme' => 'islandora_solr_metadata_description',
    ] + $elements;
    return $markup;
  }
  else {
    return FALSE;
  }
}
